# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_chlorosityfromrws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlorosityfromrws',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
