# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20170410_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='chlorosityfromrws',
            name='category',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chlorosityfromrws',
            name='time',
            field=models.IntegerField(),
        ),
    ]
