# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_chlorosityfromrws_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chlorosityfromrws',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='chlorosityfromrws',
            name='category',
        ),
    ]
