# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='tide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterName', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default=1)),
                ('locationName', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
